.TL
Buddycheck Repair
.AU
Connor Spruit (6449611)
.AU
(Team 13)

.NH 1
Team Performance rating
.TS 
tab(;) allbox;
cccccc.
person; job performance; leadership/initiative; time management; interaction; knowledge;
self;4;4;3;4;4;
calin;4;3;4;4;5;
kristian;5;4;5;4;5;
lara;5;4;4;5;5;
flip;3;3;4;3;3;
.TE

.NH 1
Messages to Peers
.NH 2
Calin
.NH 3
Strengths
.PP
During the implementation of Websockets, you really dug in to figure out,
how they worked and how they should be implemented, setting down a great example of robustness and reliability: 
I have seen the websockets break a grand total of 1 time, in a tested scenario on a different computer.
In addition, you delivered everything nicely ahead of schedule with exceptional quality.
.NH 3
Weaknesses
.PP
I found your leadership and initiative leave something to be desired.
During meetings, you would often be quiet and involve yourself very little with other people's topics,
and you share your opinion rarely unless the conversation was about a feature assigned to you. 
While not disastrous, sharing your opinion and taking a bit more initiative would have helped the team be more focused and directed instead of a few individuals suggesting a heading and people like you almost blindly agreeing to it. To improve this, dare share your opinion a bit more often and take an interest into the project as a whole instead of just focusing on your own parts.
.NH 2
Kristian
.NH 3
Strengths
.PP
I found it very inspiring how you took initiative. During meetings you were always very involved,
offering to do more than just your own parts, always suggesting ideas and trying to help other team members. 
In addition, you did more than required, providing the foundations of the project in addition to your other responsibilities, 
and everything, always, ahead of schedule.
.NH 3
Weaknesses
.PP 
While I do not have much in the way of complaints. 
During meetings, you would sometimes get a little overexcited and make a suggestion you would yourself admit just a few seconds later makes very little sense.
I'm unable to name a direct example, but you would often suggest doing things in complicated "fun" way that would add needless complexity to the project.
When someone would then say 'Hey that doesn't make sense' you'd be quick to admit it.
As I said, I never found it a major issue but it did needlessly hamper meetings little.
Keeping the meeting serious and on point would have made them go just a little smoother.
.NH 2
Lara
.NH 3
Strengths
.PP
I found that your experience with the course,
combined with the fact you do not shy away from taking ownership or initiative is very helpful.
It provided a lot of insight into how operations within the team should be structured.
During meetings, you were a driving force even if it was not your meeting, and you always made sure everything that needed to be figured out was discussed, 
within time yet thoroughly.
.NH 3
Weaknesses
.PP 
Especially at the beginning of the project, you had a tendency to be late, hampering our ability to conduct meetings.
Improving on-time performance would help a lot.
.NH 2
Flip
.NH 3
Strengths
.PP
I think you did a phenomenal job implementing the 'meaningful addition' for searching. 
Especially given the time frame I think you implemented a well-thought-out feature in very little time. 
I found it very impressive.
.NH 3
Weaknesses
.PP
I found that during meetings you would often be a bit quiet and lacking some initiative. 
While it's not a show-stopper, I do think it impacted the team negatively, since the input you did give was always very useful and carefully thought out,
I think you could have used more of that.
In the future, try sharing a bit more of what you are thinking and your opinion on certain matters.
