.TL
Buddycheck Repair
.AU
Connor Spruit (6449611)
.AU
(Team 13)

.NH 1
Team Performance rating
.TS 
tab(;) allbox;
cccccc.
person; job performance; leadership/initiative; time management; interaction; knowledge;
self;4;4;3;4;4;
calin;4;3;4;4;5;
kristian;5;4;5;4;5;
lara;5;4;4;5;5;
flip;3;3;4;3;3;
.TE

.NH 1
Mesages to Peers
.NH 2
Calin
.NH 3
Strengths
.PP
During the implementation of Websockets you really dug in to figure out,
how the worked and how they should be implemented setting down a great example of robustness and reliablilty: 
I have seen the websockets break a grand total of 1 time, in a tested senario on a different computer.
In addition you delivered everything nicely adhead of shedual with exceptional quality.
.NH 3
Weaknesses
.PP
I found your leadership and initiative leave something to be desired,
during meetings you would often be quiet and involve yourself very little with other peoples topics,
and you share your opinion rarely unless the conversation was about a feature assigned to you. 
While not desasterous sharing your opinion and taking a bit more initiative would have helped out the team be more focused and directed instead of a few individuals sugesting a heading and people like you almost blindly agreeing to it. To improve this, dare share your opinion a bit more often and take an interest into the project as a whole instead of just focusing on your own parts.
.NH 2
Kristian
.NH 3
Strenths
.PP
I found it very inspiring how you took initiative, during meetings you were always very involved,
offering to do more than just your own parts, always suggesting ideas and trying to help other team members. 
In addition you did more than required, providing the foundations of the project in addition to your other responsibilities, 
and everything, always, ahead of schedual.
.NH 3
Weaknessess
.PP 
While I do not have much in the way of complaints. 
During meetings you would sometimes get a little overexcited and make a sugestion you would yourself admit just a few seconds later makes very little sense.
I'm unable to name a direct example but you would often sugest doing things the complicated way "fun" way that would add needless complexity to the project.
When someone would then say 'hey that doesn't make sense' you'd be quick to admit it.
As I said it was never a major issue but it did needlessly hamper meetings little bit.
Keeping the meeting serious and on-point would have make them go just a little smoother.
.NH 2
Lara
.NH 3
Strengths
.PP
I found your experience with the course,
combined with the fact you do not shy away from taking ownership or initiative very helpfull,
as it provided a lot of insight into how operations within the team should be structured.
During meetings you were a driving force even if it was not your meeting and you always made sure everything that needed to be figured out was discussed, 
within time yet throughly.
.NH 3
Weaknessess
.PP 
Esspecially at the beginning of the project you had a tendency to be late, hampering our ability to conduct meetings.
Improving on-time performance would help a lot.
.NH 2
Flip
.NH 3
Strengths
.PP

.NH 3
Weaknessess
.PP
Lorum Ipsum
