.TL 
CSE2115 Peer assignment #1
.AU
Connor Spruit
.AU
Dominykas Vaskevicius
.AI
Technische Universiteit Delft
.NH
Version
.PP
We listened to
.B 
Thomas Overklift Vaupel Klein
.R
in Flux hall B, covering the second year software project

.NH
Problem statement
.PP
Lorum ipsum


.NH 
Identifying stakeholders
.PP
.IP \[bu]
.B
students
.R
have to find project proposals and sign up for teams
.IP \[bu]
.B 
clients
.R 
have to submit project proposals and select teams
.IP \[bu]
.B
(co-)coordinators
.R
have to accept or reject proposals, manage team formation and coordinate (under more) TA and supervisor assignment
.IP \[bu]
The
.B
program coordinator
.R
has to accept or reject students based on entry requirements and exhemptions
.IP \[bu]
.B
teaching assitants
.R
have to find their assigned group and be able to help the team
.IP \[bu]
.B
supervisors
.R 
have to be able to see everything the team is doing


.NH 
User stories
.NH 2
Students
.PP
.IP \[bu]
I want to be able to view available projects
.IP \[bu]
I want to be able to contact my superviors or TA's
.IP \[bu]
I want to be able to show interest in project proposals so I can form a group with other interested students
.IP \[bu]
I need to be able to see my feedback and the associated rubics and grades
.IP \[bu]
I want to be able to sign up with the team we already formed
.IP \[bu]
I want to be able to freely & anonimously exprees feedback about my teammates to my supervisor
.IP \[bu]
I need to be able to fill in and sign the contract
.IP \[bu]
I want to be able to collect my payment if applicable
.IP \[bu]
.NH 2
clients
.IP \[bu]
I want to be able to submit a project proposal
.IP \[bu]
I want to be able to pick which team does my project if multiple teams apply
.IP \[bu]
I want to be able to see how the project is going
.IP \[bu]
I want to be able to fill in, review and sign the contract(s)
.IP \[bu]
I want to be able to view and pay any payments to the university and students in a easy way
.IP \[bu]
I want to sign a contract so i'm protected by law
.NH 2
(Co-)Coordinators
.IP \[bu]
I want to be able to manage all the contracts that need to be signed in one place so I don't have to keep mailing pdf's around.IP \[bu]
.IP \[bu]
I want other parties to be able to submit their feedback to me so we can take all opinions into account and be prepared for the grade disscussions
.IP \[bu]
I want to be able to export all grades so I can import them in mytudelft
.IP \[bu]
I want to be able to view submitted project proposals and to be able to accept or reject them
.NH 2
Programmecoordinator
.IP \[bu]
I want to be able to view applying students and if they meet the entry requirements
.NH 2
supervisor
.IP \[bu]
I want to be able to see what my team is doing

.NH
Refining requirements
.PP
Lorum Ipsum

.NH 
Reflection
.NH 2
A: Is an interview the best way to elicid requirements?
.PP
Bla die bla yeah it's good for getting a lot of info quick but it's not the best because not in depth, 1 interview is stupid and things can be contradictory
.NH 2
B: sugest an alternative or addition to interviewing as elicitation.
.PP
for a large body of ppl ofc questionaire bla bla. observing people doing what they do will be way better but it will take way more time

 
